codepkg/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CTP_CaseType__c</fullName>
        <description>This field specifies the type of case.</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Merit review</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Misc. Claims</fullName>
                </value>
                <value>
                    <fullName>DRS</fullName>
                </value>
                <value>
                    <fullName>CAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTP_Feedback_Sub_type__c</fullName>
        <description>Created as part of DCR-308 to store sub-type for Feedback type of Case</description>
        <label>Feedback Sub-type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CTP_Feedback_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Motor Accident Injury Claims</fullName>
                </value>
                <value>
                    <fullName>Making a Claims</fullName>
                </value>
                <value>
                    <fullName>Insurance Policies</fullName>
                </value>
                <value>
                    <fullName>The CTP Scheme</fullName>
                </value>
                <value>
                    <fullName>Green Slips</fullName>
                </value>
                <value>
                    <fullName>Claims Disputes</fullName>
                </value>
                <value>
                    <fullName>Our Contact Support Services</fullName>
                </value>
                <value>
                    <fullName>Our Dispute Resolution Services</fullName>
                </value>
                <value>
                    <fullName>CTP Green Slip</fullName>
                </value>
                <value>
                    <fullName>About my Insurer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTP_Feedback_Type__c</fullName>
        <description>Created as part of DCR-308.</description>
        <label>Feedback Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Compliment</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTP_Response_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created as part of DCr-308 to store the preference for  response required for Feedback case</description>
        <label>Response Required</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

codepkg/objects/CTP_CaseTypeMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store Case Type and its field mapping</description>
    <fields>
        <fullName>CTP_Case_Type__c</fullName>
        <description>Field to store case type values</description>
        <label>Case Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_Origin__c</fullName>
        <description>Field to store origin value</description>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_Priority__c</fullName>
        <description>Field to store priority value</description>
        <label>Priority</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_RecordType__c</fullName>
        <description>Field to store record type of case</description>
        <label>RecordType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_Status__c</fullName>
        <description>Field to store Feedback Status</description>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CaseTypeMapping</label>
</CustomObject>

codepkg/objects/CTP_FeedbackTypeSubType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to store feedback type and feedback sub type</description>
    <fields>
        <fullName>CTP_Case_Type__c</fullName>
        <description>Field to store the case type</description>
        <label>Case Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_Feedback_SubType__c</fullName>
        <description>Field to store feedbackSubType for Custom Setting</description>
        <label>Feedback SubType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_Feedback_Type__c</fullName>
        <description>Field to store feedback type for custom setting</description>
        <label>Feedback Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FeedbackTypeSubTypeMapping</label>
</CustomObject>

codepkg/classes/CTP_FetchFeedbackFormController.cls
//Apex Controller class for CTP_Feedback Form component
public class CTP_FetchFeedbackFormController { 
    
    //Method:To retrieve Feedback Type picklist values from metadata
    @AuraEnabled
    public static List < String > getselectOptions(string fld) {
        List < String > allOpts = new list < String > ();
        // Get the list of picklist values for this field.
        list < Schema.PicklistEntry > values =
            Case.getSObjectType().getDescribe().fields.getMap().get(fld).getDescribe().getPickListValues(); 
        // Add these values to the selectoption list.
        for (Schema.PicklistEntry a: values) {
            allOpts.add(a.getValue());
        }
        return allOpts;
    }
    
    //Method to retireve feedback sub-type dependent picklist values from custom setting 
    @AuraEnabled
    public static List<String> getDependentOptions(string masterValue){
        List<String> options = new List<String>();
        Map<String,List<String>> feedbackTypesMap =  new  Map<String,List<String>> ();
        List<String> fsubtypeListForEnquiry = new List<String>();
        Set<String> fsubtypeSetForFeedbackOrComplaint = new Set<String>();
        List<String> fsubtypeListForFeedbackOrComplaint = new List<String>();
        List<String> fsubtypeListForCompliment = new List<String>();
        
        For(CTP_FeedbackTypeSubType__c obj: [Select CTP_Feedback_Type__c,CTP_Feedback_SubType__c from CTP_FeedbackTypeSubType__c]){ 
            if(obj.CTP_Feedback_Type__c == Label.CTP_Enquiry){
                fsubtypeListForEnquiry.add(obj.CTP_Feedback_SubType__c);
            }
            if(obj.CTP_Feedback_Type__c == Label.CTP_Feedback || obj.CTP_Feedback_Type__c == Label.CTP_Complaint){
                fsubtypeSetForFeedbackOrComplaint.add(obj.CTP_Feedback_SubType__c);
            }
            
            if(obj.CTP_Feedback_Type__c == Label.CTP_Compliment){
                fsubtypeListForCompliment.add(obj.CTP_Feedback_SubType__c);
            }         
        }
        if(fsubtypeListForEnquiry.size()>0){
            feedbackTypesMap.put(Label.CTP_Enquiry,fsubtypeListForEnquiry);
        }
        if(fsubtypeSetForFeedbackOrComplaint.size()>0){
            for(String s:fsubtypeSetForFeedbackOrComplaint){
                fsubtypeListForFeedbackOrComplaint.add(s);
            }
            feedbackTypesMap.put(Label.CTP_Feedback,fsubtypeListForFeedbackOrComplaint);
            feedbackTypesMap.put(Label.CTP_Complaint,fsubtypeListForFeedbackOrComplaint);
        }
        if(fsubtypeListForCompliment.size()>0){
            feedbackTypesMap.put(Label.CTP_Compliment,fsubtypeListForCompliment);
        }
        
        List<String> fsubTypeList = new List<String>();
        fsubTypeList = feedbackTypesMap.get(masterValue);
        for(String s:fsubTypeList){
            options.add(s);
        }
        return options;
    }
    
    //Method: To check 'CAS' or 'DRS' type of cases based on picklist values selected in dropdown values from custom setting
    @AuraEnabled
    public static string checkCaseType(String feedbackType , String feedbackSubType ,String descValue, Boolean respValue){
        Case caseDetail= new Case();
        try{
            CTP_FeedbackTypeSubType__c fTypeCaseType = [Select CTP_Feedback_Type__c,CTP_Feedback_SubType__c,CTP_Case_Type__c from CTP_FeedbackTypeSubType__c where CTP_Feedback_SubType__c=:feedbackSubType AND CTP_Feedback_Type__c=:feedbackType LIMIT 1];
            String csid =  createCase(fTypeCaseType.CTP_Case_Type__c,feedbackType,feedbackSubType,descValue,respValue);
            caseDetail=[Select CaseNumber from case where id=:csid];
        }
        catch(Exception e){
            system.debug('message>>>'+e);
        }
        
        return caseDetail.CaseNumber;
    }
    //Method: To create 'CAS' or 'DRS' type of cases based on picklist values selected in dropdown values.
    @AuraEnabled
    public static string createCase(String caseType ,String feedbackType,String feedbackSubType,String descValue ,Boolean respValue){
        Case csObj = new Case();
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.useDefaultRule= true;
        CTP_CaseTypeMapping__c newCaseInfo = [Select CTP_Status__c,CTP_Origin__c,CTP_Priority__c,CTP_RecordType__c,CTP_Case_Type__c from CTP_CaseTypeMapping__c where CTP_Case_Type__c=:caseType LIMIT 1];
        Id CSFRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(newCaseInfo.CTP_RecordType__c).getRecordTypeId(); 
        csObj.RecordTypeId= CSFRecordTypeId ;
        csObj.CTP_CaseType__c = newCaseInfo.CTP_Case_Type__c;
        csObj.Status = newCaseInfo.CTP_Status__c;
        csObj.Origin = newCaseInfo.CTP_Origin__c;
        csObj.Priority = newCaseInfo.CTP_Priority__c;
        csObj.setOptions(dmlOpts ); 
        csObj.CTP_Feedback_Type__c = feedbackType;
        csObj.CTP_Feedback_Sub_type__c = feedbackSubType;
        csObj.description = descValue;
        csObj.CTP_Response_Required__c = respValue;
        insert csObj; 
        return csObj.id;
    }  
}