codepkg/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CTP_Feedback_Sub_type__c</fullName>
        <description>Created as part of DCR-308 to store sub-type for Feedback type of Case</description>
        <label>Feedback Sub-type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>CTP_Feedback_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Motor Accident Injury Claims</fullName>
                </value>
                <value>
                    <fullName>Making a Claims</fullName>
                </value>
                <value>
                    <fullName>Insurance Policies</fullName>
                </value>
                <value>
                    <fullName>The CTP Scheme</fullName>
                </value>
                <value>
                    <fullName>Green Slips</fullName>
                </value>
                <value>
                    <fullName>Claims Disputes</fullName>
                </value>
                <value>
                    <fullName>Our Contact Support Services</fullName>
                </value>
                <value>
                    <fullName>Our Dispute Resolution Services</fullName>
                </value>
                <value>
                    <fullName>CTP Green Slip</fullName>
                </value>
                <value>
                    <fullName>About my Insurer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTP_Feedback_Type__c</fullName>
        <description>Created as part of DCR-308.</description>
        <label>Feedback Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enquiry</fullName>
                </value>
                <value>
                    <fullName>Feedback</fullName>
                </value>
                <value>
                    <fullName>Compliment</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

codepkg/classes/CTP_AcceptCaseController_Test.cls
@isTest
public class CTP_AcceptCaseController_Test {
    static testMethod void testAcceptCaseController() {
        Group testGroup = new Group(Name='CTP_CAS_Feedback', Type='Queue');
        insert testGroup;
        System.runAs(new User(Id=UserInfo.getUserId()))
        {
            QueuesObject testQueue = new QueueSObject(QueueID = testGroup.id, SObjectType = 'Case');
            insert testQueue;
        }
        Case csObj = new Case();
        csObj.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Feedback').getRecordTypeId(); 
        csObj.OwnerId =testGroup.id;
        csObj.status = 'New';
        csObj.Origin = 'Post';
        csObj.CTP_Feedback_Type__c = 'Enquiry';
        csObj.CTP_Feedback_Sub_type__c = 'Motor Accident Injury Claims';
        csObj.Description = 'Test Case';
        insert csObj;     
        
        Test.StartTest();
        CTP_AcceptCaseController.checkOwner(csObj.id);
        system.assertEquals(true, CTP_AcceptCaseController.checkOwner(csObj.id));
        CTP_AcceptCaseController.acceptCase(csObj.id);
        system.assertEquals(true, CTP_AcceptCaseController.acceptCase(csObj.id));
        test.stopTest();   
    }
}