codepkg/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Accident_Location__c</fullName>
        <label>Location of Accident</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_CaseSubStatus__c</fullName>
        <description>This field provides information about the case sub status</description>
        <label>Case Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Application received</fullName>
                </value>
                <value>
                    <fullName>Application verification</fullName>
                </value>
                <value>
                    <fullName>Screening</fullName>
                </value>
                <value>
                    <fullName>Awaiting Reply</fullName>
                </value>
                <value>
                    <fullName>Triage</fullName>
                </value>
                <value>
                    <fullName>Appropriate Dispute Resolution</fullName>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Analysis</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
                <value>
                    <fullName>QA</fullName>
                </value>
                <value>
                    <fullName>Account payable</fullName>
                </value>
                <value>
                    <fullName>Finalised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTP_CaseSubType__c</fullName>
        <description>This field provides information about the case sub type</description>
        <label>Case Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Application received</fullName>
                </value>
                <value>
                    <fullName>Acceptance verification</fullName>
                </value>
                <value>
                    <fullName>Screening</fullName>
                </value>
                <value>
                    <fullName>Awaiting Reply</fullName>
                </value>
                <value>
                    <fullName>Triage</fullName>
                </value>
                <value>
                    <fullName>ADR</fullName>
                </value>
                <value>
                    <fullName>Allocated</fullName>
                </value>
                <value>
                    <fullName>Analysis</fullName>
                </value>
                <value>
                    <fullName>Hearing</fullName>
                </value>
                <value>
                    <fullName>Decision</fullName>
                </value>
                <value>
                    <fullName>QA</fullName>
                </value>
                <value>
                    <fullName>Account payable</fullName>
                </value>
                <value>
                    <fullName>Finalise</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTP_ClaimNumber__c</fullName>
        <description>Holds claim number provided by insurer for a particular claim</description>
        <label>Claim Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_Date_of_accident__c</fullName>
        <description>Created as part of DCR-20 for new submitted application</description>
        <label>Date of accident</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CTP_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CTP_InjuredPersonContact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Claimant Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Claimant Contact)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CTP_InsurerInternalReviewDone__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to specify if Insurer internal review has been completed by the Insurer</description>
        <label>Has the insurer done an internal review?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CTP_Insurer_name__c</fullName>
        <description>Created as part of DCR-20 for new submitted application</description>
        <label>Insurer name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_ReviewCompletionDate__c</fullName>
        <description>Created as part of DCR-236, User provides the date when insurer internal review was done, populated from claimant portal.</description>
        <label>Insurer internal review date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CTP_ReviewReceiptDate__c</fullName>
        <description>Created as part of DCR-236, User provides the date of receipt of insurer internal review, populated from claimant portal.</description>
        <label>Insurer internal review receipt date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CTP_Time_When_Application_Lodged__c</fullName>
        <label>Time When Application Lodged</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_outline_what_it_is_that_you_dont_agr__c</fullName>
        <description>Reasons for claimant&apos;s application for dispute and disagreements with the insurer&apos;s internal review decision.
Created as part of DCR-20.</description>
        <inlineHelpText>Outline what it is that you don&apos;t agree with in the Insurer&apos;s Decision and how you think it should be different</inlineHelpText>
        <label>How do you disagree with the insurer?</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Claimant_Name__c</fullName>
        <description>Name of claimant for whom the application has been submitted. This is derived from UCD.</description>
        <label>Claimant Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CTP_Application</fullName>
        <active>true</active>
        <businessProcess>Application level</businessProcess>
        <description>The means by which a party refers a merit review matter, medical assessment matter, misc claims assessment matter and claims assessment matter.</description>
        <label>Application</label>
    </recordTypes>
</CustomObject>

codepkg/classes/CTP_UCDDetailsController.cls
public without sharing class CTP_UCDDetailsController {
    //public static CTP_UDCResponseWrapper ucdObj;
    @Auraenabled
    public static CTP_UDCResponseWrapper getUcddetails()
    {
        CTP_UDCResponseWrapper responseObj=new CTP_UDCResponseWrapper();
        responseObj.Claimnumber='123456';
        responseObj.Claimantname='Sally Robinson';
        responseObj.Dateofaccident='15/12/2017';
        responseObj.Locationofaccident='NSW 2000';
        responseObj.InsurerName = 'QBE';
        System.debug('@@@@'+responseObj);
        //ucdObj = responseObj;
        return responseObj;
    }
    
    @Auraenabled
    public static String createCaseRecord(String reviewCompletion,String reviewRecept,String ClaimNumber, String disagreementReason ,String ucdObj)
    {
        reviewCompletion = reviewCompletion.remove('"');
        List<String> reviewCompletionDateParts = reviewCompletion.split('-');
        Date reviewCompletionDate = Date.newInstance(Integer.valueOf(reviewCompletionDateParts[0]), Integer.valueOf(reviewCompletionDateParts[1]), Integer.valueOf(reviewCompletionDateParts[2]));
        
        reviewRecept = reviewRecept.remove('"');
        List<String> reviewReceptDateParts = reviewRecept.split('-');
        Date reviewReceptDate = Date.newInstance(Integer.valueOf(reviewReceptDateParts[0]), Integer.valueOf(reviewReceptDateParts[1]), Integer.valueOf(reviewReceptDateParts[2]));
        
        CTP_UDCResponseWrapper ucdRecord = (CTP_UDCResponseWrapper)JSON.deserialize(ucdobj,CTP_UDCResponseWrapper.class);
        String dateOfAccident = ucdRecord.Dateofaccident;
        List<String> accidentDateParts = dateOfAccident.split('/');
        Date accidentDate = Date.newInstance(Integer.valueOf(accidentDateParts[2]), Integer.valueOf(accidentDateParts[1]), Integer.valueOf(accidentDateParts[0]));
        System.Debug('@@@=============='+reviewCompletion+reviewRecept+ClaimNumber+disagreementReason+ucdObj);
        AssignmentRule AR = new AssignmentRule();
        AR = [select id from AssignmentRule where SobjectType = 'Case' and Active = true limit 1];
        
        //Creating the DMLOptions for "Assign using active assignment rules" checkbox
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;
        
        Case caseObj=new Case();
        
        caseObj.RecordTypeId=[Select id from Recordtype where sobjecttype='Case' and DeveloperName='CTP_Application'].id;
        caseObj.Status='Lodgement';
        caseObj.CTP_CaseSubStatus__c='Application received';
        caseObj.CTP_CaseSubType__c='Application received';
        caseObj.Origin='Web';
        caseObj.Priority='Low';
        caseobj.Subject = 'Web form application';
        User usr = [select Id , ContactId from User where Id =: UserInfo.getUserId()];

        caseobj.CTP_InjuredPersonContact__c = usr.ContactId;
        caseObj.ClaimNumber__c=ClaimNumber;
        ///caseObj.CTP_Claim_Number__c=String.valueof(ClaimNumber);
        caseObj.CTP_ReviewCompletionDate__c= reviewCompletionDate;
        caseObj.CTP_ReviewReceiptDate__c= reviewReceptDate;
        caseObj.CTP_Insurer_name__c = ucdRecord.InsurerName;
        caseObj.CTP_Date_of_accident__c=accidentDate;
        caseObj.CTP_outline_what_it_is_that_you_dont_agr__c = disagreementReason;
        caseObj.setOptions(dmlOpts);
        caseObj.CTP_Email__c=[Select Email from User where id=:UserInfo.getUserId() limit 1].Email;
        caseObj.CTP_InsurerInternalReviewDone__c=true;
        caseObj.CTP_Time_When_Application_Lodged__c = Datetime.now().format('hh:mm:ss a');
        caseObj.CTP_ClaimNumber__c=ClaimNumber;
        caseObj.Claimant_Name__c=ucdRecord.Claimantname;
        //caseObj.CTP_Location_of_accident__latitude__s=33.8688;
        //caseObj.CTP_Location_of_accident__longitude__s=151.2093;
        caseObj.Accident_Location__c = ucdRecord.Locationofaccident;
        caseObj.DateTimeCaseLodged__c = System.now();
        System.Debug('@@@'+caseObj);
        try
        {
            insert caseObj;
            String caseId=caseObj.id;
            Case cas = [Select id,CaseNumber,Contact.Email from Case where id=:caseId limit 1];
            return caseObj.id;
        }
        catch(Exception e)
        {
            return '12312312';
        } 
    }
    
    
}