codepkg/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CTP_ActionAndOutcome__c</fullName>
        <label>Action and Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Introduction Call</fullName>
                </value>
                <value>
                    <fullName>10 week Call</fullName>
                </value>
                <value>
                    <fullName>23 week Call</fullName>
                </value>
                <value>
                    <fullName>Claimant has been contacted</fullName>
                </value>
                <value>
                    <fullName>No Answer</fullName>
                </value>
                <value>
                    <fullName>Claimant does not want to be contacted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTP_CaseType__c</fullName>
        <description>This field specifies the type of case.</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Merit review</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Misc. Claims</fullName>
                </value>
                <value>
                    <fullName>DRS</fullName>
                </value>
                <value>
                    <fullName>CAS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CTP_Date_of_accident__c</fullName>
        <description>Created as part of DCR-20 for new submitted application</description>
        <label>Date of accident</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CTP_InjuredPersonContact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Claimant Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Claimant Contact)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CTP_LodgementDate__c</fullName>
        <label>Lodgement Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

codepkg/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>InterpreterRequired__c</fullName>
        <description>Accessibility Field: Do you require an interpreter?</description>
        <label>Interpreter Required?</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>Worker requires an interpreter who speaks the entered language</description>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Chinese (Simplified)</fullName>
                </value>
                <value>
                    <fullName>Chinese (Traditional)</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

codepkg/objects/CTP_CaseRecordTypeEntitlementMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom Setting to Map Case Record Type and Entitlement process</description>
    <fields>
        <fullName>CTP_Case_Record_Type__c</fullName>
        <description>Field to store case record type</description>
        <label>CTP Case Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTP_Entitlement_Process_Name__c</fullName>
        <description>Name of entitlement process</description>
        <label>CTP Entitlement Process Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CTP_CaseRecordTypeEntitlementMapping</label>
</CustomObject>

codepkg/classes/CTP_CaseTriggerhandler_Test.cls
/*********************
 * Test Class : CTP_CaseTriggerhandler_Test
 * Class : CTP_CaseTriggerhandler
 * Purpose : 
 * Author : Sudha Kumari
 * *******************************/
@isTest(seeAllData=false)
private class CTP_CaseTriggerhandler_Test {
    static testMethod void testCaseBeforeInsert(){
        List<RecordType> rcType = [select id,name from RecordType where sObjectType = 'case' and Name = 'Feedback'];
        Account acc = new account();
        acc.Name = 'Test Account';
        insert acc;
       
        Contact con = new Contact();
        con.lastName = 'Test Contact';
        Con.accountId = acc.Id;
        con.InterpreterRequired__c = 'Yes';
        con.Language__c = 'English';
        insert con;
        
        Entitlement ent = new Entitlement();
        ent.Name = 'CTP Feedback PS';
        ent.AccountId = acc.id;
        insert ent;
        
        CTP_CaseRecordTypeEntitlementMapping__c CaseEMap= new CTP_CaseRecordTypeEntitlementMapping__c();
        CaseEMap.Name = '1';
        CaseEMap.CTP_Case_Record_Type__c = 'Feedback';
        CaseEMap.CTP_Entitlement_Process_Name__c = 'CTP Feedback PS'; 
        insert CaseEMap; 
        
        Case cs = new case();
        cs.CTP_InjuredPersonContact__c = con.id;
        cs.recordTypeId = rcType[0].id;
        cs.status = 'Introduction Call';
        cs.CTP_Next_Action_Status__c = 'Must Call';
       // cs.CTP_ActionAndOutcome__c = 'Unable to Contact';
        insert cs;      
        
        Case csAfterTrigger = [select id , entitlementId from case limit 1];
        System.assertEquals(csAfterTrigger.EntitlementID,ent.id);
                
    }
    static testMethod void testCaseAfterUpdate(){
        List<RecordType> rcType = [select id,name from RecordType where sObjectType = 'case' and Name = 'CTP Assist - Claimant Support'];
        List<Group> queueObj= [select Id from Group where NAME = 'CTP Assist Feedback' Limit 1];
        List<User> userList = [select id from user where user.Profile.name ='CTP Claims Advisor' limit 1];
        Account acc = new account();
        acc.Name = 'Test Account';
        insert acc;
       
        Contact con = new Contact();
        con.lastName = 'Test Contact';
        Con.accountId = acc.Id;
        con.InterpreterRequired__c = 'Yes';
        con.Language__c = 'English';
        insert con;
        
        Entitlement ent = new Entitlement();
        ent.Name = 'CTP Feedback PS';
        ent.AccountId = acc.id;
        insert ent;
                
        CTP_CaseRecordTypeEntitlementMapping__c CaseEMap= new CTP_CaseRecordTypeEntitlementMapping__c();
        CaseEMap.Name = '2';
        CaseEMap.CTP_Case_Record_Type__c = 'CTP Assist - Claimant Support';
        CaseEMap.CTP_Entitlement_Process_Name__c = 'CTP Feedback PS'; 
        insert CaseEMap; 
        
        Case cs = new case();
        cs.CTP_InjuredPersonContact__c = con.id;
        cs.recordTypeId = rcType[0].id;
        cs.CTP_Date_of_accident__c = system.today() - 1;
        cs.CTP_LodgementDate__c = system.today();
        cs.status = 'Introduction Call';
        cs.CTP_Next_Action_Status__c = 'Must Call';
        cs.CTP_ActionAndOutcome__c = 'Unable to Contact';
        //cs.OwnerId = queueObj[0].id;
        cs.OwnerId = userList[0].id;
        cs.CTP_CaseType__c = 'CAS';
        insert cs;
        
        Case csAfterTrigger = [select id , entitlementId from case limit 1];
        System.assertEquals(csAfterTrigger.EntitlementID,ent.id);
        
        
       /* CaseMilestone cMStone = new CaseMilestone();
        cMStone.MilestoneType.Name = 'CTP Milestone 1 26-Week Entitlement';
      //  cMStone.caseId = cs.id;
        insert cMStone;   */
        
        List<CaseMilestone> cmsToUpdate = [select Id, completionDate from CaseMilestone where (MilestoneType.Name='CTP Milestone 1 26-Week Entitlement' OR MilestoneType.Name='CTP Milestone 2 26-Week Entitlement' OR MilestoneType.Name='CTP Milestone 3 26-Week Entitlement') and completionDate = null];
            
        cs.status = '10 week call';
        cs.CTP_ActionAndOutcome__c = 'Claimant does not want to be contacted';
        Update cs;
      
        cs.status = '23 week call';
        Update cs;
        
        cs.status = 'Introduction Call';
       // cs.CTP_ActionAndOutcome__c = 'Unable to Contact';
        Update cs;
    }

}